# Lecture 2

Learning goals
- review while statements
- if statements
- introduce pandas
- introduce matplotlib

## Fibonacci sequence: review of loops

The Fibonacci sequence is the sequence of numbers generated by applying the rules:

$a_1 = a_2 = 1, a_i = a_{i-2} + a_{i-1}$

So, after the first two values, each number in the sequence is the sum of the previous two.

### for loops
Add comments to each of the lines below, describing what each line does.
Remember that, in the example below, `i` is known as an _index_.
This kind of indexing within a `for` loop is very common.

In [4]:
fib_sequence = np.full(n_values, np.nan)
fib_sequence[0] = 1
fib_sequence[1] = 1
fib_sequence[2] = fib_sequence[2-2] + fib_sequence[2-1]
fib_sequence[3] = fib_sequence[3-2] + fib_sequence[3-1]

fib_sequence


array([ 1.,  1.,  2.,  3., nan, nan, nan, nan, nan, nan])

In [15]:
# Fibonacci sequence with a for loop
import numpy as np  # Import and load the critical numpy module

n_values = 10
fib_sequence = np.full(n_values, np.nan)
fib_sequence[0] = 1
fib_sequence[1] = 1

for i in range(2, n_values):
    fib_sequence[i] = fib_sequence[i-2] + fib_sequence[i-1]

print(fib_sequence)

[ 1.  1.  2.  3.  5.  8. 13. 21. 34. 55.]


+ What is the _type_ of the variable `fib_sequence`?
+ What sorts of values are contained within this variable
(i.e., what is the type of a single element of this variable)?
+ What happens if we don't _recast_ `fib_sequence` as an integer in the last line of the cell above?

### if statements and logicals/booleans
The result of a comparison between two different objects is a _boolean_ object, 
and takes the value of either `True` or `False`.

Potential comparison operators are

| Operator | Comparison |
| --- | ---      |
| ==  | Equal to |
| !=  | Not equal to |
| >   | Greater than |
| <   | Less than    |
| >=  | Greater than or equal to |
| <=  | Less than or equal to |

In [19]:
7 == 8

False

In [20]:
'apple' == ['kiwi', 'apple', 'orange']

False

In [22]:
for fruit in ['kiwi', 'apple', 'orange']:
    print('apple' == fruit)

False
True
False


An `if` statement executes if a following comparison is `True`.

In [26]:
for x in range(3, 10, 3):
    if x <= 3:
        print(x, 'is less than or equal to three')
    elif x > 5:
        print(x, 'is greater than five')
#    else:
        #print('I guess', x, 'is either four or five')

3 is less than or equal to three
6 is greater than five
9 is greater than five


### while loops
While loops continue to execute so long as a condition is met through some kind of comparison at the top of the loop.
That is, while the condition is `True`, the loop will just keep executing again and again.

Add comments to each of the lines below, describing what each line does, and why it was necessary

In [28]:
i = 1
while i < 7.3:
    print(i)
    i = i+2


1
3
5
7


In [34]:
# Fibonacci sequence with a while loop
max_value = 1000

fib_sequence = [1, 1]

while fib_sequence[-2] + fib_sequence[-1] <= max_value:
    fib_sequence.append(fib_sequence[-2] + fib_sequence[-1])
    
print(fib_sequence)
print( np.array(fib_sequence) )

fib_sequence = np.array(fib_sequence)

[1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144, 233, 377, 610, 987]
[  1   1   2   3   5   8  13  21  34  55  89 144 233 377 610 987]


+ What is the _type_ of the variable `fib_sequence`?
+ What sorts of values are contained within this variable
(i.e., what is the type of a single element of this variable)?
+ _Lists_ in python are not as flexible and useful as _numpy.ndarrays_. To recast the list as an _ndarray_, you can use the function np.array() and enclose the list within the parentheses.  Do this in the cell below.

## In class exercise: Folding paper to the moon
You have an exceptionally large piece of paper.  This paper is 0.1 mm thick.
How many times would you have to fold it to get a stack of folded paper that
could reach from the surface of the Earth to the Moon?

Assume that you have unbounded strength, and that you can fold any stack of paper exactly back on itself!

In [39]:
moon_dist = 400000 * 1e6 # mm Distance from Earth to Moon in mm

paper_stack = [0.1] # mm  List of the thicknesses of the folded paper
    # 0.1 when 0 folds, 0.2 when 1 folds, 0.4 ....
    # number_of_folds = len(paper_stack)-1

while paper_stack[-1] <= moon_dist:
    # add value to the list that is the previous paper_stack height times 2
    paper_stack.append( paper_stack[-1] * 2 ) 

number_of_folds = len(paper_stack)-1
print(number_of_folds)
print(paper_stack[-1] / 1e6, ' km')

42
439804.65111040004  km


In [46]:
num_of_paper_sheets = moon_dist / paper_stack[0]
num_of_paper_sheets
folds = np.log2(num_of_paper_sheets)
print( np.ceil(folds).astype(int) )

42


## In class exercise: Identifying leap years
In the Gregorian calendar, a year is a _leap year_ if it is divisible by 4,
with the exception that years divisible by 100 are _not_ leap years unless they are
also divisible by 400.

Write a Python program that determines if `year` is a leap year.

For this exercise, you'll find the Python modulo operator useful.
This operator, `%` in python, returns the remainder of division.
``` python
3 % 4 = 3
11 % 5 = 1
```

In [ ]:
year = 2019

## Pandas for tabular data and Matplotlib for plotting

Below is a line overlying a DEM of the northwestern region.
The elevations approximately along the location of this line are shown in the csv file `NW_elev_profile.csv`

This profile starts in the Pacific Ocean, passes near Mt. St. Helens and Mt. Adams, 
crosses the Columbia Plateau, the Palouse near Moscow, the Bitterroot Mountains, and then the Little Belt Mountains of Montana.
![Topographic profile through the US Northwest](profile_location.png "Profile location")

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
df = pd.read_csv('NW_elev_profile.csv')
df

In [ ]:
df.describe()

In [ ]:
df.dtypes

In [ ]:
dist = df['Distance (m)'].to_numpy() # m
elev = df['Elevation (m)'].to_numpy() # m

In [ ]:
%matplotlib inline
fig, ax = plt.subplots()

ax.plot(dist, elev)
ax.set_xlabel('Distance (m)')
ax.set_title('East-west profile through the Northwest')

Improve on the plot above by using more methods of the `ax` object to modify the axes of the figure and its labels.

Use the matplotlib text() function to add annotations to the plot identifying mountain ranges and valleys
that you can recognize https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.text.html

+ Create figure that shows the topographic slopes as a function of distance along the profile.  
+ Can you calculate the slopes over different _windows_ to better capture the broad trends versus the details of each mountain side?